feat: add benchmark repetition
RafaelGSS/bench-node pull request #27
Opened 2024-12-10 03:49 UTC by gusanthiago

Hello there, this is related to this issue https://github.com/RafaelGSS/bench-node/issues/6.

This PR aims to introduce benchmark repetition as an optional parameter. By running benchmarks multiple times and averaging the results, we can minimize noise and improve the accuracy of the measurements.

Below, you’ll find a comparison of benchmarks with repetition versus those without:
```
 node --allow-natives-syntax examples/create-uint32array/node.js
```

<img width="1375" alt="Screenshot 2024-12-10 at 00 43 49" src="https://github.com/user-attachments/assets/f95bdd5a-92c3-45c4-990b-caed79f3173f">

Let me know if needs add something, thanks :)

2024-12-10 14:02 UTC, RafaelGSS requested changes
Hey! Thanks for the PR

I'd just rename the "repetitions" to "repeatSuite". We run the benchmark multiple times already (benchmark runs * samples) and adding an option with that name would be misleading.

2024-12-10 14:03 UTC, RafaelGSS commented
Could you also update the docs?

2024-12-10 21:24 UTC, gusanthiago commented
Sure @RafaelGSS , I believe makes sense, I gonna update the docs and rename it

2024-12-11 04:17 UTC, RafaelGSS approved these changes
LGTM

2024-12-11 04:40 UTC, merged